name: action-test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: notion update
        working-directory: ./notion
        run: |
          npm install
          npm run update
      # - run: echo "123" > sample.txt
      # - uses: EndBug/add-and-commit@v9
      #   with:
      #     message: 'botbotbot'
      #     add: 'sample.txt'
