name: action-test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: echo "123" > sample.txt

      - uses: EndBug/add-and-commit@v9
        with:
          message: 'botbotbot'
          add: 'sample.txt'
